services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
      - worker

  redis:
    image: redis:8.2-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A cities_weather worker --loglevel=info
    env_file:
      - ./.env
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis